#!/bin/bash

flatpak-builder -v \
	--force-clean \
	--disable-rofiles-fuse \
	--ccache \
	--repo=repo \
	--subject="Build of com.ozmartians.VidCutter `date`" \
	./build \
	com.ozmartians.VidCutter.json
