name: vidcutter
version: 6.0.5.1
type: app
base: core20
architectures:
    - amd64
summary: the simplest + fastest media cutter and joiner
description: |
    A modern, simple to use, constantly evolving and 
    hella fast MEDIA CUTTER + JOINER w/ frame-accurate
    SmartCut technology + Qt5, libmpv, FFmpeg and
    MediaInfo powering the backend.

icon: data/icons/hicolor/512x512/apps/com.ozmartians.VidCutter.png

grade: stable
confinement: strict

plugs:
    browser-sandbox:
        allow-sandbox: false
        interface: browser-support
    gsettings: null
    gtk-3-themes:
        default-provider: gtk-common-themes
        interface: content
        target: $SNAP/data-dir/themes
    icon-themes:
        default-provider: gtk-common-themes
        interface: content
        target: $SNAP/data-dir/icons
    sound-themes:
        default-provider: gtk-common-themes
        interface: content
        target: $SNAP/data-dir/sounds

apps:
    vidcutter:
        command: bin/desktop-launch $SNAP/bin/vidcutter
        plugs: [unity7, x11, wayland, desktop, desktop-legacy, home, audio-playback, pulseaudio, gsettings, opengl, mount-observe, network, network-bind, network-manager, network-observe, raw-usb, removable-media, screen-inhibit-control]
        desktop: share/applications/com.ozmartians.VidCutter.desktop
        environment:
            PYTHONPATH: $SNAP/usr/lib/python3/dist-packages
            LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/samba:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/vdpau:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri
            # QT_QPA_PLATFORMTHEME: gtk3
            # DISABLE_WAYLAND: 1

parts:
    prepare:
        plugin: nil
        build-packages:
            - software-properties-common
        # override-build: |
        #     add-apt-repository ppa:savoury1/ffmpeg4 -y
        #     add-apt-repository ppa:savoury1/mpv -y
        #     apt update
        #     apt upgrade -yy
        prime: [-*]

    desktop-qt5:
        source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
        source-subdir: qt
        plugin: make
        after: [prepare]
        make-parameters: ["FLAVOR=qt5"]
        build-packages:
            - build-essential
            - qtbase5-dev
            - dpkg-dev
        stage-packages:
            - libxkbcommon0
            - ttf-ubuntu-font-family
            - dmz-cursor-theme
            - light-themes
            - adwaita-icon-theme
            - gnome-themes-standard
            - shared-mime-info
            - libqt5gui5
            - qt5-style-plugins
            - libgdk-pixbuf2.0-0
            - mesa-vdpau-drivers
            - libvdpau-va-gl1
            - libglu1-mesa
            - libdb5.3
            - libqt5svg5 # for loading icon themes which are svg
            - try: [appmenu-qt5] # not available on core18
            - locales-all
            - xdg-user-dirs
            - libgtk2.0-0
            - libslang2
            - qt5-gtk-platformtheme
            - qtwayland5

    vidcutter:
        plugin: python
        source: .
        after: [prepare, desktop-qt5]
        build-packages:
            - python3-dev
            - python3-setuptools
            - libmpv-dev
        stage-packages:
            - python3-pyqt5
            - python3-pyqt5.qtx11extras
            - python3-opengl
            - python3-simplejson
            - libmpv1
            - ffmpeg
            - mediainfo
            - libslang2
            - libblas3
            - qt5-gtk-platformtheme
            - qtwayland5
