name: vidcutter
version: 3.5.0
summary: the simplest + fastest video cutter & joiner
description: |
    The simplest & sexiest tool for cutting and
    joining your videos without the need for re-encoding
    or a diploma in multimedia. VidCutter focuses on
    getting the job done using tried and true tech in its
    arsenal via mpv and FFmpeg.

grade: devel
confinement: devmode

apps:
  vidcutter:
    command: env LC_ALL=C.UTF-8 desktop-launch $SNAP/vidcutter
    plugs: [home, pulseaudio, x11, opengl]

parts:
  vidcutter:
    plugin: python
    plugin-version: python3
    process-dependency-links: false
    source: https://github.com/ozmartian/vidcutter/archive/3.5.0.tar.gz
    after: [desktop-qt5]
    build-packages:
        - python3-dev
        - python3-setuptools
    stage-packages:
        - python3-pyqt5
        - libmpv1
        - ffmpeg
        - mediainfo
    prepare: sed -i "s/pypi/deb/" "vidcutter/__init__.py"
